# Generated by Django 2.2.4 on 2019-09-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_auto_20190919_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
