# Generated by Django 2.2.4 on 2019-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0003_auto_20190919_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='my_shop/images'),
        ),
    ]
