# Generated by Django 2.2.4 on 2019-09-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0004_auto_20190919_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Iteam',
        ),
    ]
